<?php

use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Municipios
         DB::table('municipios')->insert([
			['departamento_id'=>'1' , 'codigo_divipola'=> '001' , 'nombre'=> 'MEDELLIN'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '002' , 'nombre'=> 'ABEJORRAL'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '004' , 'nombre'=> 'ABRIAQUI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '021' , 'nombre'=> 'ALEJANDRIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '030' , 'nombre'=> 'AMAGA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '031' , 'nombre'=> 'AMALFI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '034' , 'nombre'=> 'ANDES'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '036' , 'nombre'=> 'ANGELOPOLIS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '038' , 'nombre'=> 'ANGOSTURA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '040' , 'nombre'=> 'ANORI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '042' , 'nombre'=> 'SANTAFE DE ANTIOQUIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '044' , 'nombre'=> 'ANZA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '045' , 'nombre'=> 'APARTADO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '051' , 'nombre'=> 'ARBOLETES'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '055' , 'nombre'=> 'ARGELIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '059' , 'nombre'=> 'ARMENIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '079' , 'nombre'=> 'BARBOSA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '086' , 'nombre'=> 'BELMIRA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '088' , 'nombre'=> 'BELLO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '091' , 'nombre'=> 'BETANIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '093' , 'nombre'=> 'BETULIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '101' , 'nombre'=> 'CIUDAD BOLIVAR'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '107' , 'nombre'=> 'BRICEÑO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '113' , 'nombre'=> 'BURITICA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '120' , 'nombre'=> 'CACERES'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '125' , 'nombre'=> 'CAICEDO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '129' , 'nombre'=> 'CALDAS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '134' , 'nombre'=> 'CAMPAMENTO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '138' , 'nombre'=> 'CAÑASGORDAS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '142' , 'nombre'=> 'CARACOLI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '145' , 'nombre'=> 'CARAMANTA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '147' , 'nombre'=> 'CAREPA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '148' , 'nombre'=> 'EL CARMEN DE VIBORAL'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '150' , 'nombre'=> 'CAROLINA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '154' , 'nombre'=> 'CAUCASIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '172' , 'nombre'=> 'CHIGORODO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '190' , 'nombre'=> 'CISNEROS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '197' , 'nombre'=> 'COCORNA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '206' , 'nombre'=> 'CONCEPCION'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '209' , 'nombre'=> 'CONCORDIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '212' , 'nombre'=> 'COPACABANA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '234' , 'nombre'=> 'DABEIBA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '237' , 'nombre'=> 'DON MATIAS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '240' , 'nombre'=> 'EBEJICO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL BAGRE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '264' , 'nombre'=> 'ENTRERRIOS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '266' , 'nombre'=> 'ENVIGADO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '282' , 'nombre'=> 'FREDONIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '284' , 'nombre'=> 'FRONTINO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '306' , 'nombre'=> 'GIRALDO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '308' , 'nombre'=> 'GIRARDOTA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '310' , 'nombre'=> 'GOMEZ PLATA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '313' , 'nombre'=> 'GRANADA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '315' , 'nombre'=> 'GUADALUPE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUARNE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '321' , 'nombre'=> 'GUATAPE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '347' , 'nombre'=> 'HELICONIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '353' , 'nombre'=> 'HISPANIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '360' , 'nombre'=> 'ITAGUI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '361' , 'nombre'=> 'ITUANGO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '364' , 'nombre'=> 'JARDIN'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '368' , 'nombre'=> 'JERICO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '376' , 'nombre'=> 'LA CEJA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '380' , 'nombre'=> 'LA ESTRELLA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '390' , 'nombre'=> 'LA PINTADA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '400' , 'nombre'=> 'LA UNION'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '411' , 'nombre'=> 'LIBORINA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '425' , 'nombre'=> 'MACEO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '440' , 'nombre'=> 'MARINILLA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '467' , 'nombre'=> 'MONTEBELLO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '475' , 'nombre'=> 'MURINDO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '480' , 'nombre'=> 'MUTATA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '483' , 'nombre'=> 'NARIÑO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '490' , 'nombre'=> 'NECOCLI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '495' , 'nombre'=> 'NECHI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '501' , 'nombre'=> 'OLAYA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '541' , 'nombre'=> 'PEÐOL'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '543' , 'nombre'=> 'PEQUE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '576' , 'nombre'=> 'PUEBLORRICO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '579' , 'nombre'=> 'PUERTO BERRIO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '585' , 'nombre'=> 'PUERTO NARE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '591' , 'nombre'=> 'PUERTO TRIUNFO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '604' , 'nombre'=> 'REMEDIOS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '607' , 'nombre'=> 'RETIRO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '615' , 'nombre'=> 'RIONEGRO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '628' , 'nombre'=> 'SABANALARGA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '631' , 'nombre'=> 'SABANETA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '642' , 'nombre'=> 'SALGAR'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '647' , 'nombre'=> 'SAN ANDRES DE CUERQUIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '649' , 'nombre'=> 'SAN CARLOS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '652' , 'nombre'=> 'SAN FRANCISCO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '656' , 'nombre'=> 'SAN JERONIMO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '658' , 'nombre'=> 'SAN JOSE DE LA MONTAÑA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '659' , 'nombre'=> 'SAN JUAN DE URABA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '660' , 'nombre'=> 'SAN LUIS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '664' , 'nombre'=> 'SAN PEDRO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '665' , 'nombre'=> 'SAN PEDRO DE URABA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '667' , 'nombre'=> 'SAN RAFAEL'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAN ROQUE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '674' , 'nombre'=> 'SAN VICENTE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '679' , 'nombre'=> 'SANTA BARBARA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '686' , 'nombre'=> 'SANTA ROSA DE OSOS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '690' , 'nombre'=> 'SANTO DOMINGO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '697' , 'nombre'=> 'EL SANTUARIO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '736' , 'nombre'=> 'SEGOVIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '756' , 'nombre'=> 'SONSON'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '761' , 'nombre'=> 'SOPETRAN'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '789' , 'nombre'=> 'TAMESIS'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '790' , 'nombre'=> 'TARAZA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '792' , 'nombre'=> 'TARSO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '809' , 'nombre'=> 'TITIRIBI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '819' , 'nombre'=> 'TOLEDO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '837' , 'nombre'=> 'TURBO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '842' , 'nombre'=> 'URAMITA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '847' , 'nombre'=> 'URRAO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '854' , 'nombre'=> 'VALDIVIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '856' , 'nombre'=> 'VALPARAISO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '858' , 'nombre'=> 'VEGACHI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '861' , 'nombre'=> 'VENECIA'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '873' , 'nombre'=> 'VIGIA DEL FUERTE'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '885' , 'nombre'=> 'YALI'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '887' , 'nombre'=> 'YARUMAL'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '890' , 'nombre'=> 'YOLOMBO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '893' , 'nombre'=> 'YONDO'],
			['departamento_id'=>'1' , 'codigo_divipola'=> '895' , 'nombre'=> 'ZARAGOZA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '001' , 'nombre'=> 'BARRANQUILLA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '078' , 'nombre'=> 'BARANOA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '137' , 'nombre'=> 'CAMPO DE LA CRUZ'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '141' , 'nombre'=> 'CANDELARIA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '296' , 'nombre'=> 'GALAPA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '372' , 'nombre'=> 'JUAN DE ACOSTA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '421' , 'nombre'=> 'LURUACO'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '433' , 'nombre'=> 'MALAMBO'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '436' , 'nombre'=> 'MANATI'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '520' , 'nombre'=> 'PALMAR DE VARELA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '549' , 'nombre'=> 'PIOJO'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '558' , 'nombre'=> 'POLONUEVO'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '560' , 'nombre'=> 'PONEDERA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '573' , 'nombre'=> 'PUERTO COLOMBIA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '606' , 'nombre'=> 'REPELON'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '634' , 'nombre'=> 'SABANAGRANDE'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '638' , 'nombre'=> 'SABANALARGA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '675' , 'nombre'=> 'SANTA LUCIA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '685' , 'nombre'=> 'SANTO TOMAS'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '758' , 'nombre'=> 'SOLEDAD'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '770' , 'nombre'=> 'SUAN'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '832' , 'nombre'=> 'TUBARA'],
			['departamento_id'=>'2' , 'codigo_divipola'=> '849' , 'nombre'=> 'USIACURI'],
			['departamento_id'=>'3' , 'codigo_divipola'=> '001' , 'nombre'=> 'BOGOTA, D.C.'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '001' , 'nombre'=> 'CARTAGENA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '006' , 'nombre'=> 'ACHI'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '030' , 'nombre'=> 'ALTOS DEL ROSARIO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '042' , 'nombre'=> 'ARENAL'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '052' , 'nombre'=> 'ARJONA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '062' , 'nombre'=> 'ARROYOHONDO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '074' , 'nombre'=> 'BARRANCO DE LOBA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '140' , 'nombre'=> 'CALAMAR'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '160' , 'nombre'=> 'CANTAGALLO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '188' , 'nombre'=> 'CICUCO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '212' , 'nombre'=> 'CORDOBA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '222' , 'nombre'=> 'CLEMENCIA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '244' , 'nombre'=> 'EL CARMEN DE BOLIVAR'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '248' , 'nombre'=> 'EL GUAMO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '268' , 'nombre'=> 'EL PEÑON'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '300' , 'nombre'=> 'HATILLO DE LOBA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '430' , 'nombre'=> 'MAGANGUE'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '433' , 'nombre'=> 'MAHATES'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '440' , 'nombre'=> 'MARGARITA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '442' , 'nombre'=> 'MARIA LA BAJA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '458' , 'nombre'=> 'MONTECRISTO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '468' , 'nombre'=> 'MOMPOS'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '490' , 'nombre'=> 'NOROSI'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '473' , 'nombre'=> 'MORALES'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '549' , 'nombre'=> 'PINILLOS'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '580' , 'nombre'=> 'REGIDOR'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '600' , 'nombre'=> 'RIO VIEJO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '620' , 'nombre'=> 'SAN CRISTOBAL'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '647' , 'nombre'=> 'SAN ESTANISLAO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '650' , 'nombre'=> 'SAN FERNANDO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '654' , 'nombre'=> 'SAN JACINTO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '655' , 'nombre'=> 'SAN JACINTO DEL CAUCA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '657' , 'nombre'=> 'SAN JUAN NEPOMUCENO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '667' , 'nombre'=> 'SAN MARTIN DE LOBA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAN PABLO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '673' , 'nombre'=> 'SANTA CATALINA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '683' , 'nombre'=> 'SANTA ROSA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '688' , 'nombre'=> 'SANTA ROSA DEL SUR'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '744' , 'nombre'=> 'SIMITI'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '760' , 'nombre'=> 'SOPLAVIENTO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '780' , 'nombre'=> 'TALAIGUA NUEVO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '810' , 'nombre'=> 'TIQUISIO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '836' , 'nombre'=> 'TURBACO'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '838' , 'nombre'=> 'TURBANA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '873' , 'nombre'=> 'VILLANUEVA'],
			['departamento_id'=>'4' , 'codigo_divipola'=> '894' , 'nombre'=> 'ZAMBRANO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '001' , 'nombre'=> 'TUNJA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '022' , 'nombre'=> 'ALMEIDA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '047' , 'nombre'=> 'AQUITANIA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '051' , 'nombre'=> 'ARCABUCO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '087' , 'nombre'=> 'BELEN'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '090' , 'nombre'=> 'BERBEO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '092' , 'nombre'=> 'BETEITIVA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '097' , 'nombre'=> 'BOAVITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '104' , 'nombre'=> 'BOYACA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '106' , 'nombre'=> 'BRICEÑO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '109' , 'nombre'=> 'BUENAVISTA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '114' , 'nombre'=> 'BUSBANZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '131' , 'nombre'=> 'CALDAS'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '135' , 'nombre'=> 'CAMPOHERMOSO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '162' , 'nombre'=> 'CERINZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '172' , 'nombre'=> 'CHINAVITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '176' , 'nombre'=> 'CHIQUINQUIRA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '180' , 'nombre'=> 'CHISCAS'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '183' , 'nombre'=> 'CHITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '185' , 'nombre'=> 'CHITARAQUE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '187' , 'nombre'=> 'CHIVATA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '189' , 'nombre'=> 'CIENEGA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '204' , 'nombre'=> 'COMBITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '212' , 'nombre'=> 'COPER'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '215' , 'nombre'=> 'CORRALES'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '218' , 'nombre'=> 'COVARACHIA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '223' , 'nombre'=> 'CUBARA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '224' , 'nombre'=> 'CUCAITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '226' , 'nombre'=> 'CUITIVA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '232' , 'nombre'=> 'CHIQUIZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '236' , 'nombre'=> 'CHIVOR'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '238' , 'nombre'=> 'DUITAMA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '244' , 'nombre'=> 'EL COCUY'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '248' , 'nombre'=> 'EL ESPINO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '272' , 'nombre'=> 'FIRAVITOBA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '276' , 'nombre'=> 'FLORESTA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '293' , 'nombre'=> 'GACHANTIVA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '296' , 'nombre'=> 'GAMEZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '299' , 'nombre'=> 'GARAGOA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '317' , 'nombre'=> 'GUACAMAYAS'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '322' , 'nombre'=> 'GUATEQUE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '325' , 'nombre'=> 'GUAYATA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '332' , 'nombre'=> 'GsICAN'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '362' , 'nombre'=> 'IZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '367' , 'nombre'=> 'JENESANO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '368' , 'nombre'=> 'JERICO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '377' , 'nombre'=> 'LABRANZAGRANDE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '380' , 'nombre'=> 'LA CAPILLA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '401' , 'nombre'=> 'LA VICTORIA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '403' , 'nombre'=> 'LA UVITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '407' , 'nombre'=> 'VILLA DE LEYVA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '425' , 'nombre'=> 'MACANAL'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '442' , 'nombre'=> 'MARIPI'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '455' , 'nombre'=> 'MIRAFLORES'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '464' , 'nombre'=> 'MONGUA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '466' , 'nombre'=> 'MONGUI'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '469' , 'nombre'=> 'MONIQUIRA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '476' , 'nombre'=> 'MOTAVITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '480' , 'nombre'=> 'MUZO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '491' , 'nombre'=> 'NOBSA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '494' , 'nombre'=> 'NUEVO COLON'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '500' , 'nombre'=> 'OICATA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '507' , 'nombre'=> 'OTANCHE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '511' , 'nombre'=> 'PACHAVITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '514' , 'nombre'=> 'PAEZ'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '516' , 'nombre'=> 'PAIPA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '518' , 'nombre'=> 'PAJARITO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '522' , 'nombre'=> 'PANQUEBA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '531' , 'nombre'=> 'PAUNA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '533' , 'nombre'=> 'PAYA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '537' , 'nombre'=> 'PAZ DE RIO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '542' , 'nombre'=> 'PESCA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '550' , 'nombre'=> 'PISBA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '572' , 'nombre'=> 'PUERTO BOYACA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '580' , 'nombre'=> 'QUIPAMA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '599' , 'nombre'=> 'RAMIRIQUI'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '600' , 'nombre'=> 'RAQUIRA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '621' , 'nombre'=> 'RONDON'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '632' , 'nombre'=> 'SABOYA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '638' , 'nombre'=> 'SACHICA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '646' , 'nombre'=> 'SAMACA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '660' , 'nombre'=> 'SAN EDUARDO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '664' , 'nombre'=> 'SAN JOSE DE PARE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '667' , 'nombre'=> 'SAN LUIS DE GACENO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '673' , 'nombre'=> 'SAN MATEO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '676' , 'nombre'=> 'SAN MIGUEL DE SEMA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '681' , 'nombre'=> 'SAN PABLO DE BORBUR'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '686' , 'nombre'=> 'SANTANA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '690' , 'nombre'=> 'SANTA MARIA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '693' , 'nombre'=> 'SANTA ROSA DE VITERBO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '696' , 'nombre'=> 'SANTA SOFIA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '720' , 'nombre'=> 'SATIVANORTE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '723' , 'nombre'=> 'SATIVASUR'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '740' , 'nombre'=> 'SIACHOQUE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '753' , 'nombre'=> 'SOATA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '755' , 'nombre'=> 'SOCOTA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '757' , 'nombre'=> 'SOCHA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '759' , 'nombre'=> 'SOGAMOSO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '761' , 'nombre'=> 'SOMONDOCO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '762' , 'nombre'=> 'SORA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '763' , 'nombre'=> 'SOTAQUIRA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '764' , 'nombre'=> 'SORACA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '774' , 'nombre'=> 'SUSACON'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '776' , 'nombre'=> 'SUTAMARCHAN'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '778' , 'nombre'=> 'SUTATENZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '790' , 'nombre'=> 'TASCO'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '798' , 'nombre'=> 'TENZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '804' , 'nombre'=> 'TIBANA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '806' , 'nombre'=> 'TIBASOSA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '808' , 'nombre'=> 'TINJACA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '810' , 'nombre'=> 'TIPACOQUE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '814' , 'nombre'=> 'TOCA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '816' , 'nombre'=> 'TOGsI'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '820' , 'nombre'=> 'TOPAGA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '822' , 'nombre'=> 'TOTA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '832' , 'nombre'=> 'TUNUNGUA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '835' , 'nombre'=> 'TURMEQUE'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '837' , 'nombre'=> 'TUTA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '839' , 'nombre'=> 'TUTAZA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '842' , 'nombre'=> 'UMBITA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '861' , 'nombre'=> 'VENTAQUEMADA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '879' , 'nombre'=> 'VIRACACHA'],
			['departamento_id'=>'5' , 'codigo_divipola'=> '897' , 'nombre'=> 'ZETAQUIRA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '001' , 'nombre'=> 'MANIZALES'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '013' , 'nombre'=> 'AGUADAS'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '042' , 'nombre'=> 'ANSERMA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '050' , 'nombre'=> 'ARANZAZU'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '088' , 'nombre'=> 'BELALCAZAR'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '174' , 'nombre'=> 'CHINCHINA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '272' , 'nombre'=> 'FILADELFIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '380' , 'nombre'=> 'LA DORADA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '388' , 'nombre'=> 'LA MERCED'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '433' , 'nombre'=> 'MANZANARES'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '442' , 'nombre'=> 'MARMATO'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '444' , 'nombre'=> 'MARQUETALIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '446' , 'nombre'=> 'MARULANDA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '486' , 'nombre'=> 'NEIRA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '495' , 'nombre'=> 'NORCASIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '513' , 'nombre'=> 'PACORA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '524' , 'nombre'=> 'PALESTINA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '541' , 'nombre'=> 'PENSILVANIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '614' , 'nombre'=> 'RIOSUCIO'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '616' , 'nombre'=> 'RISARALDA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '653' , 'nombre'=> 'SALAMINA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '662' , 'nombre'=> 'SAMANA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '665' , 'nombre'=> 'SAN JOSE'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '777' , 'nombre'=> 'SUPIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '867' , 'nombre'=> 'VICTORIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '873' , 'nombre'=> 'VILLAMARIA'],
			['departamento_id'=>'6' , 'codigo_divipola'=> '877' , 'nombre'=> 'VITERBO'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '001' , 'nombre'=> 'FLORENCIA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '029' , 'nombre'=> 'ALBANIA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '094' , 'nombre'=> 'BELEN DE LOS ANDAQUIES'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '150' , 'nombre'=> 'CARTAGENA DEL CHAIRA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '205' , 'nombre'=> 'CURILLO'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '247' , 'nombre'=> 'EL DONCELLO'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '256' , 'nombre'=> 'EL PAUJIL'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '410' , 'nombre'=> 'LA MONTAÑITA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '460' , 'nombre'=> 'MILAN'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '479' , 'nombre'=> 'MORELIA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '592' , 'nombre'=> 'PUERTO RICO'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '610' , 'nombre'=> 'SAN JOSE DEL FRAGUA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '753' , 'nombre'=> 'SAN VICENTE DEL CAGUAN'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '756' , 'nombre'=> 'SOLANO'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '785' , 'nombre'=> 'SOLITA'],
			['departamento_id'=>'7' , 'codigo_divipola'=> '860' , 'nombre'=> 'VALPARAISO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '001' , 'nombre'=> 'POPAYAN'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '022' , 'nombre'=> 'ALMAGUER'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '050' , 'nombre'=> 'ARGELIA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '075' , 'nombre'=> 'BALBOA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '100' , 'nombre'=> 'BOLIVAR'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '110' , 'nombre'=> 'BUENOS AIRES'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '130' , 'nombre'=> 'CAJIBIO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '137' , 'nombre'=> 'CALDONO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '142' , 'nombre'=> 'CALOTO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '212' , 'nombre'=> 'CORINTO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '256' , 'nombre'=> 'EL TAMBO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '290' , 'nombre'=> 'FLORENCIA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '300' , 'nombre'=> 'GUACHENE'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUAPI'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '355' , 'nombre'=> 'INZA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '364' , 'nombre'=> 'JAMBALO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '392' , 'nombre'=> 'LA SIERRA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '397' , 'nombre'=> 'LA VEGA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '418' , 'nombre'=> 'LOPEZ'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '450' , 'nombre'=> 'MERCADERES'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '455' , 'nombre'=> 'MIRANDA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '473' , 'nombre'=> 'MORALES'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '513' , 'nombre'=> 'PADILLA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '517' , 'nombre'=> 'PAEZ'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '532' , 'nombre'=> 'PATIA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '533' , 'nombre'=> 'PIAMONTE'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '548' , 'nombre'=> 'PIENDAMO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '573' , 'nombre'=> 'PUERTO TEJADA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '585' , 'nombre'=> 'PURACE'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '622' , 'nombre'=> 'ROSAS'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '693' , 'nombre'=> 'SAN SEBASTIAN'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '698' , 'nombre'=> 'SANTANDER DE QUILICHAO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '701' , 'nombre'=> 'SANTA ROSA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '743' , 'nombre'=> 'SILVIA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '760' , 'nombre'=> 'SOTARA'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '780' , 'nombre'=> 'SUAREZ'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '785' , 'nombre'=> 'SUCRE'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '807' , 'nombre'=> 'TIMBIO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '809' , 'nombre'=> 'TIMBIQUI'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '821' , 'nombre'=> 'TORIBIO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '824' , 'nombre'=> 'TOTORO'],
			['departamento_id'=>'8' , 'codigo_divipola'=> '845' , 'nombre'=> 'VILLA RICA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '001' , 'nombre'=> 'VALLEDUPAR'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '011' , 'nombre'=> 'AGUACHICA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '013' , 'nombre'=> 'AGUSTIN CODAZZI'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '032' , 'nombre'=> 'ASTREA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '045' , 'nombre'=> 'BECERRIL'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '060' , 'nombre'=> 'BOSCONIA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '175' , 'nombre'=> 'CHIMICHAGUA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '178' , 'nombre'=> 'CHIRIGUANA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '228' , 'nombre'=> 'CURUMANI'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '238' , 'nombre'=> 'EL COPEY'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL PASO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '295' , 'nombre'=> 'GAMARRA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '310' , 'nombre'=> 'GONZALEZ'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '383' , 'nombre'=> 'LA GLORIA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '400' , 'nombre'=> 'LA JAGUA DE IBIRICO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '443' , 'nombre'=> 'MANAURE'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '517' , 'nombre'=> 'PAILITAS'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '550' , 'nombre'=> 'PELAYA'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '570' , 'nombre'=> 'PUEBLO BELLO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '614' , 'nombre'=> 'RIO DE ORO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '621' , 'nombre'=> 'LA PAZ'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '710' , 'nombre'=> 'SAN ALBERTO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '750' , 'nombre'=> 'SAN DIEGO'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '770' , 'nombre'=> 'SAN MARTIN'],
			['departamento_id'=>'9' , 'codigo_divipola'=> '787' , 'nombre'=> 'TAMALAMEQUE'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '001' , 'nombre'=> 'MONTERIA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '068' , 'nombre'=> 'AYAPEL'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '079' , 'nombre'=> 'BUENAVISTA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '090' , 'nombre'=> 'CANALETE'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '162' , 'nombre'=> 'CERETE'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '168' , 'nombre'=> 'CHIMA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '182' , 'nombre'=> 'CHINU'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '189' , 'nombre'=> 'CIENAGA DE ORO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '300' , 'nombre'=> 'COTORRA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '350' , 'nombre'=> 'LA APARTADA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '417' , 'nombre'=> 'LORICA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '419' , 'nombre'=> 'LOS CORDOBAS'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '464' , 'nombre'=> 'MOMIL'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '466' , 'nombre'=> 'MONTELIBANO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '500' , 'nombre'=> 'MOÑITOS'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '555' , 'nombre'=> 'PLANETA RICA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '570' , 'nombre'=> 'PUEBLO NUEVO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '574' , 'nombre'=> 'PUERTO ESCONDIDO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '580' , 'nombre'=> 'PUERTO LIBERTADOR'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '586' , 'nombre'=> 'PURISIMA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '660' , 'nombre'=> 'SAHAGUN'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAN ANDRES SOTAVENTO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '672' , 'nombre'=> 'SAN ANTERO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '675' , 'nombre'=> 'SAN BERNARDO DEL VIENTO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '678' , 'nombre'=> 'SAN CARLOS'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '686' , 'nombre'=> 'SAN PELAYO'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '807' , 'nombre'=> 'TIERRALTA'],
			['departamento_id'=>'10' , 'codigo_divipola'=> '855' , 'nombre'=> 'VALENCIA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '001' , 'nombre'=> 'AGUA DE DIOS'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '019' , 'nombre'=> 'ALBAN'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '035' , 'nombre'=> 'ANAPOIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '040' , 'nombre'=> 'ANOLAIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '053' , 'nombre'=> 'ARBELAEZ'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '086' , 'nombre'=> 'BELTRAN'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '095' , 'nombre'=> 'BITUIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '099' , 'nombre'=> 'BOJACA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '120' , 'nombre'=> 'CABRERA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '123' , 'nombre'=> 'CACHIPAY'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '126' , 'nombre'=> 'CAJICA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '148' , 'nombre'=> 'CAPARRAPI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '151' , 'nombre'=> 'CAQUEZA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '154' , 'nombre'=> 'CARMEN DE CARUPA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '168' , 'nombre'=> 'CHAGUANI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '175' , 'nombre'=> 'CHIA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '178' , 'nombre'=> 'CHIPAQUE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '181' , 'nombre'=> 'CHOACHI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '183' , 'nombre'=> 'CHOCONTA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '200' , 'nombre'=> 'COGUA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '214' , 'nombre'=> 'COTA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '224' , 'nombre'=> 'CUCUNUBA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL COLEGIO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '258' , 'nombre'=> 'EL PEÑON'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '260' , 'nombre'=> 'EL ROSAL'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '269' , 'nombre'=> 'FACATATIVA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '279' , 'nombre'=> 'FOMEQUE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '281' , 'nombre'=> 'FOSCA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '286' , 'nombre'=> 'FUNZA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '288' , 'nombre'=> 'FUQUENE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '290' , 'nombre'=> 'FUSAGASUGA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '293' , 'nombre'=> 'GACHALA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '295' , 'nombre'=> 'GACHANCIPA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '297' , 'nombre'=> 'GACHETA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '299' , 'nombre'=> 'GAMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '307' , 'nombre'=> 'GIRARDOT'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '312' , 'nombre'=> 'GRANADA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '317' , 'nombre'=> 'GUACHETA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '320' , 'nombre'=> 'GUADUAS'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '322' , 'nombre'=> 'GUASCA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '324' , 'nombre'=> 'GUATAQUI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '326' , 'nombre'=> 'GUATAVITA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '328' , 'nombre'=> 'GUAYABAL DE SIQUIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '335' , 'nombre'=> 'GUAYABETAL'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '339' , 'nombre'=> 'GUTIERREZ'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '368' , 'nombre'=> 'JERUSALEN'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '372' , 'nombre'=> 'JUNIN'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '377' , 'nombre'=> 'LA CALERA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '386' , 'nombre'=> 'LA MESA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '394' , 'nombre'=> 'LA PALMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '398' , 'nombre'=> 'LA PEÑA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '402' , 'nombre'=> 'LA VEGA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '407' , 'nombre'=> 'LENGUAZAQUE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '426' , 'nombre'=> 'MACHETA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '430' , 'nombre'=> 'MADRID'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '436' , 'nombre'=> 'MANTA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '438' , 'nombre'=> 'MEDINA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '473' , 'nombre'=> 'MOSQUERA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '483' , 'nombre'=> 'NARIÑO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '486' , 'nombre'=> 'NEMOCON'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '488' , 'nombre'=> 'NILO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '489' , 'nombre'=> 'NIMAIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '491' , 'nombre'=> 'NOCAIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '506' , 'nombre'=> 'VENECIA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '513' , 'nombre'=> 'PACHO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '518' , 'nombre'=> 'PAIME'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '524' , 'nombre'=> 'PANDI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '530' , 'nombre'=> 'PARATEBUENO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '535' , 'nombre'=> 'PASCA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '572' , 'nombre'=> 'PUERTO SALGAR'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '580' , 'nombre'=> 'PULI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '592' , 'nombre'=> 'QUEBRADANEGRA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '594' , 'nombre'=> 'QUETAME'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '596' , 'nombre'=> 'QUIPILE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '599' , 'nombre'=> 'APULO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '612' , 'nombre'=> 'RICAURTE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '645' , 'nombre'=> 'SAN ANTONIO DEL TEQUENDAMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '649' , 'nombre'=> 'SAN BERNARDO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '653' , 'nombre'=> 'SAN CAYETANO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '658' , 'nombre'=> 'SAN FRANCISCO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '662' , 'nombre'=> 'SAN JUAN DE RIO SECO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '718' , 'nombre'=> 'SASAIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '736' , 'nombre'=> 'SESQUILE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '740' , 'nombre'=> 'SIBATE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '743' , 'nombre'=> 'SILVANIA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '745' , 'nombre'=> 'SIMIJACA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '754' , 'nombre'=> 'SOACHA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '758' , 'nombre'=> 'SOPO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '769' , 'nombre'=> 'SUBACHOQUE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '772' , 'nombre'=> 'SUESCA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '777' , 'nombre'=> 'SUPATA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '779' , 'nombre'=> 'SUSA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '781' , 'nombre'=> 'SUTATAUSA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '785' , 'nombre'=> 'TABIO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '793' , 'nombre'=> 'TAUSA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '797' , 'nombre'=> 'TENA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '799' , 'nombre'=> 'TENJO'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '805' , 'nombre'=> 'TIBACUY'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '807' , 'nombre'=> 'TIBIRITA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '815' , 'nombre'=> 'TOCAIMA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '817' , 'nombre'=> 'TOCANCIPA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '823' , 'nombre'=> 'TOPAIPI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '839' , 'nombre'=> 'UBALA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '841' , 'nombre'=> 'UBAQUE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '843' , 'nombre'=> 'VILLA DE SAN DIEGO DE UBATE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '845' , 'nombre'=> 'UNE'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '851' , 'nombre'=> 'UTICA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '862' , 'nombre'=> 'VERGARA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '867' , 'nombre'=> 'VIANI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '871' , 'nombre'=> 'VILLAGOMEZ'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '873' , 'nombre'=> 'VILLAPINZON'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '875' , 'nombre'=> 'VILLETA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '878' , 'nombre'=> 'VIOTA'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '885' , 'nombre'=> 'YACOPI'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '898' , 'nombre'=> 'ZIPACON'],
			['departamento_id'=>'11' , 'codigo_divipola'=> '899' , 'nombre'=> 'ZIPAQUIRA'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '001' , 'nombre'=> 'QUIBDO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '006' , 'nombre'=> 'ACANDI'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '025' , 'nombre'=> 'ALTO BAUDO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '050' , 'nombre'=> 'ATRATO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '073' , 'nombre'=> 'BAGADO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '075' , 'nombre'=> 'BAHIA SOLANO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '077' , 'nombre'=> 'BAJO BAUDO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '099' , 'nombre'=> 'BOJAYA'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '135' , 'nombre'=> 'EL CANTON DEL SAN PABLO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '150' , 'nombre'=> 'CARMEN DEL DARIEN'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '160' , 'nombre'=> 'CERTEGUI'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '205' , 'nombre'=> 'CONDOTO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL CARMEN DE ATRATO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL LITORAL DEL SAN JUAN'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '361' , 'nombre'=> 'ISTMINA'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '372' , 'nombre'=> 'JURADO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '413' , 'nombre'=> 'LLORO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '425' , 'nombre'=> 'MEDIO ATRATO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '430' , 'nombre'=> 'MEDIO BAUDO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '450' , 'nombre'=> 'MEDIO SAN JUAN'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '491' , 'nombre'=> 'NOVITA'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '495' , 'nombre'=> 'NUQUI'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '580' , 'nombre'=> 'RIO IRO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '600' , 'nombre'=> 'RIO QUITO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '615' , 'nombre'=> 'RIOSUCIO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '660' , 'nombre'=> 'SAN JOSE DEL PALMAR'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '745' , 'nombre'=> 'SIPI'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '787' , 'nombre'=> 'TADO'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '800' , 'nombre'=> 'UNGUIA'],
			['departamento_id'=>'12' , 'codigo_divipola'=> '810' , 'nombre'=> 'UNION PANAMERICANA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '001' , 'nombre'=> 'NEIVA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '006' , 'nombre'=> 'ACEVEDO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '013' , 'nombre'=> 'AGRADO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '016' , 'nombre'=> 'AIPE'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '020' , 'nombre'=> 'ALGECIRAS'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '026' , 'nombre'=> 'ALTAMIRA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '078' , 'nombre'=> 'BARAYA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '132' , 'nombre'=> 'CAMPOALEGRE'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '206' , 'nombre'=> 'COLOMBIA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '244' , 'nombre'=> 'ELIAS'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '298' , 'nombre'=> 'GARZON'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '306' , 'nombre'=> 'GIGANTE'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '319' , 'nombre'=> 'GUADALUPE'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '349' , 'nombre'=> 'HOBO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '357' , 'nombre'=> 'IQUIRA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '359' , 'nombre'=> 'ISNOS'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '378' , 'nombre'=> 'LA ARGENTINA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '396' , 'nombre'=> 'LA PLATA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '483' , 'nombre'=> 'NATAGA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '503' , 'nombre'=> 'OPORAPA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '518' , 'nombre'=> 'PAICOL'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '524' , 'nombre'=> 'PALERMO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '530' , 'nombre'=> 'PALESTINA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '548' , 'nombre'=> 'PITAL'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '551' , 'nombre'=> 'PITALITO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '615' , 'nombre'=> 'RIVERA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '660' , 'nombre'=> 'SALADOBLANCO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '668' , 'nombre'=> 'SAN AGUSTIN'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '676' , 'nombre'=> 'SANTA MARIA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '770' , 'nombre'=> 'SUAZA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '791' , 'nombre'=> 'TARQUI'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '797' , 'nombre'=> 'TESALIA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '799' , 'nombre'=> 'TELLO'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '801' , 'nombre'=> 'TERUEL'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '807' , 'nombre'=> 'TIMANA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '872' , 'nombre'=> 'VILLAVIEJA'],
			['departamento_id'=>'13' , 'codigo_divipola'=> '885' , 'nombre'=> 'YAGUARA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '001' , 'nombre'=> 'RIOHACHA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '035' , 'nombre'=> 'ALBANIA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '078' , 'nombre'=> 'BARRANCAS'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '090' , 'nombre'=> 'DIBULLA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '098' , 'nombre'=> 'DISTRACCION'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '110' , 'nombre'=> 'EL MOLINO'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '279' , 'nombre'=> 'FONSECA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '378' , 'nombre'=> 'HATONUEVO'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '420' , 'nombre'=> 'LA JAGUA DEL PILAR'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '430' , 'nombre'=> 'MAICAO'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '560' , 'nombre'=> 'MANAURE'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '650' , 'nombre'=> 'SAN JUAN DEL CESAR'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '847' , 'nombre'=> 'URIBIA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '855' , 'nombre'=> 'URUMITA'],
			['departamento_id'=>'14' , 'codigo_divipola'=> '874' , 'nombre'=> 'VILLANUEVA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '001' , 'nombre'=> 'SANTA MARTA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '030' , 'nombre'=> 'ALGARROBO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '053' , 'nombre'=> 'ARACATACA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '058' , 'nombre'=> 'ARIGUANI'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '161' , 'nombre'=> 'CERRO SAN ANTONIO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '170' , 'nombre'=> 'CHIBOLO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '189' , 'nombre'=> 'CIENAGA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '205' , 'nombre'=> 'CONCORDIA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL BANCO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '258' , 'nombre'=> 'EL PIÑON'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '268' , 'nombre'=> 'EL RETEN'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '288' , 'nombre'=> 'FUNDACION'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUAMAL'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '460' , 'nombre'=> 'NUEVA GRANADA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '541' , 'nombre'=> 'PEDRAZA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '545' , 'nombre'=> 'PIJIÑO DEL CARMEN'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '551' , 'nombre'=> 'PIVIJAY'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '555' , 'nombre'=> 'PLATO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '570' , 'nombre'=> 'PUEBLOVIEJO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '605' , 'nombre'=> 'REMOLINO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '660' , 'nombre'=> 'SABANAS DE SAN ANGEL'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '675' , 'nombre'=> 'SALAMINA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '692' , 'nombre'=> 'SAN SEBASTIAN DE BUENAVISTA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '703' , 'nombre'=> 'SAN ZENON'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '707' , 'nombre'=> 'SANTA ANA'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '720' , 'nombre'=> 'SANTA BARBARA DE PINTO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '745' , 'nombre'=> 'SITIONUEVO'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '798' , 'nombre'=> 'TENERIFE'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '960' , 'nombre'=> 'ZAPAYAN'],
			['departamento_id'=>'15' , 'codigo_divipola'=> '980' , 'nombre'=> 'ZONA BANANERA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '001' , 'nombre'=> 'VILLAVICENCIO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '006' , 'nombre'=> 'ACACIAS'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '110' , 'nombre'=> 'BARRANCA DE UPIA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '124' , 'nombre'=> 'CABUYARO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '150' , 'nombre'=> 'CASTILLA LA NUEVA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '223' , 'nombre'=> 'CUBARRAL'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '226' , 'nombre'=> 'CUMARAL'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL CALVARIO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '251' , 'nombre'=> 'EL CASTILLO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '270' , 'nombre'=> 'EL DORADO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '287' , 'nombre'=> 'FUENTE DE ORO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '313' , 'nombre'=> 'GRANADA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUAMAL'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '325' , 'nombre'=> 'MAPIRIPAN'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '330' , 'nombre'=> 'MESETAS'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '350' , 'nombre'=> 'LA MACARENA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '370' , 'nombre'=> 'URIBE'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '400' , 'nombre'=> 'LEJANIAS'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '450' , 'nombre'=> 'PUERTO CONCORDIA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '568' , 'nombre'=> 'PUERTO GAITAN'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '573' , 'nombre'=> 'PUERTO LOPEZ'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '577' , 'nombre'=> 'PUERTO LLERAS'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '590' , 'nombre'=> 'PUERTO RICO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '606' , 'nombre'=> 'RESTREPO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '680' , 'nombre'=> 'SAN CARLOS DE GUAROA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '683' , 'nombre'=> 'SAN JUAN DE ARAMA'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '686' , 'nombre'=> 'SAN JUANITO'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '689' , 'nombre'=> 'SAN MARTIN'],
			['departamento_id'=>'16' , 'codigo_divipola'=> '711' , 'nombre'=> 'VISTAHERMOSA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '001' , 'nombre'=> 'PASTO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '019' , 'nombre'=> 'ALBAN'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '022' , 'nombre'=> 'ALDANA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '036' , 'nombre'=> 'ANCUYA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '051' , 'nombre'=> 'ARBOLEDA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '079' , 'nombre'=> 'BARBACOAS'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '083' , 'nombre'=> 'BELEN'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '110' , 'nombre'=> 'BUESACO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '203' , 'nombre'=> 'COLON'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '207' , 'nombre'=> 'CONSACA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '210' , 'nombre'=> 'CONTADERO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '215' , 'nombre'=> 'CORDOBA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '224' , 'nombre'=> 'CUASPUD'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '227' , 'nombre'=> 'CUMBAL'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '233' , 'nombre'=> 'CUMBITARA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '240' , 'nombre'=> 'CHACHAGsI'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL CHARCO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '254' , 'nombre'=> 'EL PEÑOL'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '256' , 'nombre'=> 'EL ROSARIO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '258' , 'nombre'=> 'EL TABLON DE GOMEZ'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '260' , 'nombre'=> 'EL TAMBO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '287' , 'nombre'=> 'FUNES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '317' , 'nombre'=> 'GUACHUCAL'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '320' , 'nombre'=> 'GUAITARILLA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '323' , 'nombre'=> 'GUALMATAN'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '352' , 'nombre'=> 'ILES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '354' , 'nombre'=> 'IMUES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '356' , 'nombre'=> 'IPIALES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '378' , 'nombre'=> 'LA CRUZ'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '381' , 'nombre'=> 'LA FLORIDA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '385' , 'nombre'=> 'LA LLANADA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '390' , 'nombre'=> 'LA TOLA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '399' , 'nombre'=> 'LA UNION'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '405' , 'nombre'=> 'LEIVA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '411' , 'nombre'=> 'LINARES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '418' , 'nombre'=> 'LOS ANDES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '427' , 'nombre'=> 'MAGsI'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '435' , 'nombre'=> 'MALLAMA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '473' , 'nombre'=> 'MOSQUERA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '480' , 'nombre'=> 'NARIÑO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '490' , 'nombre'=> 'OLAYA HERRERA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '506' , 'nombre'=> 'OSPINA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '520' , 'nombre'=> 'FRANCISCO PIZARRO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '540' , 'nombre'=> 'POLICARPA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '560' , 'nombre'=> 'POTOSI'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '565' , 'nombre'=> 'PROVIDENCIA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '573' , 'nombre'=> 'PUERRES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '585' , 'nombre'=> 'PUPIALES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '612' , 'nombre'=> 'RICAURTE'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '621' , 'nombre'=> 'ROBERTO PAYAN'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '678' , 'nombre'=> 'SAMANIEGO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '683' , 'nombre'=> 'SANDONA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '685' , 'nombre'=> 'SAN BERNARDO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '687' , 'nombre'=> 'SAN LORENZO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '693' , 'nombre'=> 'SAN PABLO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '694' , 'nombre'=> 'SAN PEDRO DE CARTAGO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '696' , 'nombre'=> 'SANTA BARBARA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '699' , 'nombre'=> 'SANTACRUZ'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '720' , 'nombre'=> 'SAPUYES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '786' , 'nombre'=> 'TAMINANGO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '788' , 'nombre'=> 'TANGUA'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '835' , 'nombre'=> 'SAN ANDRES DE TUMACO'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '838' , 'nombre'=> 'TUQUERRES'],
			['departamento_id'=>'17' , 'codigo_divipola'=> '885' , 'nombre'=> 'YACUANQUER'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '001' , 'nombre'=> 'CUCUTA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '003' , 'nombre'=> 'ABREGO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '051' , 'nombre'=> 'ARBOLEDAS'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '099' , 'nombre'=> 'BOCHALEMA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '109' , 'nombre'=> 'BUCARASICA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '125' , 'nombre'=> 'CACOTA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '128' , 'nombre'=> 'CACHIRA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '172' , 'nombre'=> 'CHINACOTA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '174' , 'nombre'=> 'CHITAGA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '206' , 'nombre'=> 'CONVENCION'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '223' , 'nombre'=> 'CUCUTILLA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '239' , 'nombre'=> 'DURANIA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL CARMEN'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL TARRA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '261' , 'nombre'=> 'EL ZULIA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '313' , 'nombre'=> 'GRAMALOTE'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '344' , 'nombre'=> 'HACARI'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '347' , 'nombre'=> 'HERRAN'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '377' , 'nombre'=> 'LABATECA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '385' , 'nombre'=> 'LA ESPERANZA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '398' , 'nombre'=> 'LA PLAYA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '405' , 'nombre'=> 'LOS PATIOS'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '418' , 'nombre'=> 'LOURDES'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '480' , 'nombre'=> 'MUTISCUA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '498' , 'nombre'=> 'OCAÑA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '518' , 'nombre'=> 'PAMPLONA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '520' , 'nombre'=> 'PAMPLONITA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '553' , 'nombre'=> 'PUERTO SANTANDER'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '599' , 'nombre'=> 'RAGONVALIA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '660' , 'nombre'=> 'SALAZAR'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAN CALIXTO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '673' , 'nombre'=> 'SAN CAYETANO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '680' , 'nombre'=> 'SANTIAGO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '720' , 'nombre'=> 'SARDINATA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '743' , 'nombre'=> 'SILOS'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '800' , 'nombre'=> 'TEORAMA'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '810' , 'nombre'=> 'TIBU'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '820' , 'nombre'=> 'TOLEDO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '871' , 'nombre'=> 'VILLA CARO'],
			['departamento_id'=>'18' , 'codigo_divipola'=> '874' , 'nombre'=> 'VILLA DEL ROSARIO'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '001' , 'nombre'=> 'ARMENIA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '111' , 'nombre'=> 'BUENAVISTA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '130' , 'nombre'=> 'CALARCA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '190' , 'nombre'=> 'CIRCASIA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '212' , 'nombre'=> 'CORDOBA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '272' , 'nombre'=> 'FILANDIA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '302' , 'nombre'=> 'GENOVA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '401' , 'nombre'=> 'LA TEBAIDA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '470' , 'nombre'=> 'MONTENEGRO'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '548' , 'nombre'=> 'PIJAO'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '594' , 'nombre'=> 'QUIMBAYA'],
			['departamento_id'=>'19' , 'codigo_divipola'=> '690' , 'nombre'=> 'SALENTO'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '001' , 'nombre'=> 'PEREIRA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '045' , 'nombre'=> 'APIA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '075' , 'nombre'=> 'BALBOA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '088' , 'nombre'=> 'BELEN DE UMBRIA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '170' , 'nombre'=> 'DOSQUEBRADAS'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUATICA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '383' , 'nombre'=> 'LA CELIA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '400' , 'nombre'=> 'LA VIRGINIA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '440' , 'nombre'=> 'MARSELLA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '456' , 'nombre'=> 'MISTRATO'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '572' , 'nombre'=> 'PUEBLO RICO'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '594' , 'nombre'=> 'QUINCHIA'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '682' , 'nombre'=> 'SANTA ROSA DE CABAL'],
			['departamento_id'=>'20' , 'codigo_divipola'=> '687' , 'nombre'=> 'SANTUARIO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '001' , 'nombre'=> 'BUCARAMANGA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '013' , 'nombre'=> 'AGUADA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '020' , 'nombre'=> 'ALBANIA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '051' , 'nombre'=> 'ARATOCA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '077' , 'nombre'=> 'BARBOSA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '079' , 'nombre'=> 'BARICHARA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '081' , 'nombre'=> 'BARRANCABERMEJA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '092' , 'nombre'=> 'BETULIA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '101' , 'nombre'=> 'BOLIVAR'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '121' , 'nombre'=> 'CABRERA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '132' , 'nombre'=> 'CALIFORNIA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '147' , 'nombre'=> 'CAPITANEJO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '152' , 'nombre'=> 'CARCASI'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '160' , 'nombre'=> 'CEPITA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '162' , 'nombre'=> 'CERRITO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '167' , 'nombre'=> 'CHARALA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '169' , 'nombre'=> 'CHARTA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '176' , 'nombre'=> 'CHIMA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '179' , 'nombre'=> 'CHIPATA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '190' , 'nombre'=> 'CIMITARRA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '207' , 'nombre'=> 'CONCEPCION'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '209' , 'nombre'=> 'CONFINES'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '211' , 'nombre'=> 'CONTRATACION'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '217' , 'nombre'=> 'COROMORO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '229' , 'nombre'=> 'CURITI'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '235' , 'nombre'=> 'EL CARMEN DE CHUCURI'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '245' , 'nombre'=> 'EL GUACAMAYO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL PEÑON'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '255' , 'nombre'=> 'EL PLAYON'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '264' , 'nombre'=> 'ENCINO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '266' , 'nombre'=> 'ENCISO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '271' , 'nombre'=> 'FLORIAN'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '276' , 'nombre'=> 'FLORIDABLANCA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '296' , 'nombre'=> 'GALAN'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '298' , 'nombre'=> 'GAMBITA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '307' , 'nombre'=> 'GIRON'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUACA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '320' , 'nombre'=> 'GUADALUPE'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '322' , 'nombre'=> 'GUAPOTA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '324' , 'nombre'=> 'GUAVATA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '327' , 'nombre'=> 'GsEPSA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '344' , 'nombre'=> 'HATO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '368' , 'nombre'=> 'JESUS MARIA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '370' , 'nombre'=> 'JORDAN'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '377' , 'nombre'=> 'LA BELLEZA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '385' , 'nombre'=> 'LANDAZURI'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '397' , 'nombre'=> 'LA PAZ'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '406' , 'nombre'=> 'LEBRIJA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '418' , 'nombre'=> 'LOS SANTOS'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '425' , 'nombre'=> 'MACARAVITA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '432' , 'nombre'=> 'MALAGA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '444' , 'nombre'=> 'MATANZA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '464' , 'nombre'=> 'MOGOTES'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '468' , 'nombre'=> 'MOLAGAVITA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '498' , 'nombre'=> 'OCAMONTE'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '500' , 'nombre'=> 'OIBA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '502' , 'nombre'=> 'ONZAGA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '522' , 'nombre'=> 'PALMAR'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '524' , 'nombre'=> 'PALMAS DEL SOCORRO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '533' , 'nombre'=> 'PARAMO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '547' , 'nombre'=> 'PIEDECUESTA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '549' , 'nombre'=> 'PINCHOTE'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '572' , 'nombre'=> 'PUENTE NACIONAL'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '573' , 'nombre'=> 'PUERTO PARRA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '575' , 'nombre'=> 'PUERTO WILCHES'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '615' , 'nombre'=> 'RIONEGRO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '655' , 'nombre'=> 'SABANA DE TORRES'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '669' , 'nombre'=> 'SAN ANDRES'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '673' , 'nombre'=> 'SAN BENITO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '679' , 'nombre'=> 'SAN GIL'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '682' , 'nombre'=> 'SAN JOAQUIN'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '684' , 'nombre'=> 'SAN JOSE DE MIRANDA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '686' , 'nombre'=> 'SAN MIGUEL'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '689' , 'nombre'=> 'SAN VICENTE DE CHUCURI'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '705' , 'nombre'=> 'SANTA BARBARA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '720' , 'nombre'=> 'SANTA HELENA DEL OPON'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '745' , 'nombre'=> 'SIMACOTA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '755' , 'nombre'=> 'SOCORRO'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '770' , 'nombre'=> 'SUAITA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '773' , 'nombre'=> 'SUCRE'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '780' , 'nombre'=> 'SURATA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '820' , 'nombre'=> 'TONA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '855' , 'nombre'=> 'VALLE DE SAN JOSE'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '861' , 'nombre'=> 'VELEZ'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '867' , 'nombre'=> 'VETAS'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '872' , 'nombre'=> 'VILLANUEVA'],
			['departamento_id'=>'21' , 'codigo_divipola'=> '895' , 'nombre'=> 'ZAPATOCA'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '001' , 'nombre'=> 'SINCELEJO'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '110' , 'nombre'=> 'BUENAVISTA'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '124' , 'nombre'=> 'CAIMITO'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '204' , 'nombre'=> 'COLOSO'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '215' , 'nombre'=> 'COROZAL'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '221' , 'nombre'=> 'COVEÑAS'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '230' , 'nombre'=> 'CHALAN'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '233' , 'nombre'=> 'EL ROBLE'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '235' , 'nombre'=> 'GALERAS'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '265' , 'nombre'=> 'GUARANDA'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '400' , 'nombre'=> 'LA UNION'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '418' , 'nombre'=> 'LOS PALMITOS'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '429' , 'nombre'=> 'MAJAGUAL'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '473' , 'nombre'=> 'MORROA'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '508' , 'nombre'=> 'OVEJAS'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '523' , 'nombre'=> 'PALMITO'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAMPUES'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '678' , 'nombre'=> 'SAN BENITO ABAD'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '702' , 'nombre'=> 'SAN JUAN DE BETULIA'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '708' , 'nombre'=> 'SAN MARCOS'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '713' , 'nombre'=> 'SAN ONOFRE'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '717' , 'nombre'=> 'SAN PEDRO'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '742' , 'nombre'=> 'SAN LUIS DE SINCE'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '771' , 'nombre'=> 'SUCRE'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '820' , 'nombre'=> 'SANTIAGO DE TOLU'],
			['departamento_id'=>'22' , 'codigo_divipola'=> '823' , 'nombre'=> 'TOLU VIEJO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '001' , 'nombre'=> 'IBAGUE'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '024' , 'nombre'=> 'ALPUJARRA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '026' , 'nombre'=> 'ALVARADO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '030' , 'nombre'=> 'AMBALEMA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '043' , 'nombre'=> 'ANZOATEGUI'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '055' , 'nombre'=> 'ARMERO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '067' , 'nombre'=> 'ATACO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '124' , 'nombre'=> 'CAJAMARCA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '148' , 'nombre'=> 'CARMEN DE APICALA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '152' , 'nombre'=> 'CASABIANCA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '168' , 'nombre'=> 'CHAPARRAL'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '200' , 'nombre'=> 'COELLO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '217' , 'nombre'=> 'COYAIMA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '226' , 'nombre'=> 'CUNDAY'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '236' , 'nombre'=> 'DOLORES'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '268' , 'nombre'=> 'ESPINAL'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '270' , 'nombre'=> 'FALAN'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '275' , 'nombre'=> 'FLANDES'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '283' , 'nombre'=> 'FRESNO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '319' , 'nombre'=> 'GUAMO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '347' , 'nombre'=> 'HERVEO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '349' , 'nombre'=> 'HONDA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '352' , 'nombre'=> 'ICONONZO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '408' , 'nombre'=> 'LERIDA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '411' , 'nombre'=> 'LIBANO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '443' , 'nombre'=> 'MARIQUITA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '449' , 'nombre'=> 'MELGAR'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '461' , 'nombre'=> 'MURILLO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '483' , 'nombre'=> 'NATAGAIMA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '504' , 'nombre'=> 'ORTEGA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '520' , 'nombre'=> 'PALOCABILDO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '547' , 'nombre'=> 'PIEDRAS'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '555' , 'nombre'=> 'PLANADAS'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '563' , 'nombre'=> 'PRADO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '585' , 'nombre'=> 'PURIFICACION'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '616' , 'nombre'=> 'RIOBLANCO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '622' , 'nombre'=> 'RONCESVALLES'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '624' , 'nombre'=> 'ROVIRA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '671' , 'nombre'=> 'SALDAÑA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '675' , 'nombre'=> 'SAN ANTONIO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '678' , 'nombre'=> 'SAN LUIS'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '686' , 'nombre'=> 'SANTA ISABEL'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '770' , 'nombre'=> 'SUAREZ'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '854' , 'nombre'=> 'VALLE DE SAN JUAN'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '861' , 'nombre'=> 'VENADILLO'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '870' , 'nombre'=> 'VILLAHERMOSA'],
			['departamento_id'=>'23' , 'codigo_divipola'=> '873' , 'nombre'=> 'VILLARRICA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '001' , 'nombre'=> 'CALI'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '020' , 'nombre'=> 'ALCALA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '036' , 'nombre'=> 'ANDALUCIA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '041' , 'nombre'=> 'ANSERMANUEVO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '054' , 'nombre'=> 'ARGELIA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '100' , 'nombre'=> 'BOLIVAR'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '109' , 'nombre'=> 'BUENAVENTURA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '111' , 'nombre'=> 'GUADALAJARA DE BUGA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '113' , 'nombre'=> 'BUGALAGRANDE'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '122' , 'nombre'=> 'CAICEDONIA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '126' , 'nombre'=> 'CALIMA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '130' , 'nombre'=> 'CANDELARIA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '147' , 'nombre'=> 'CARTAGO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '233' , 'nombre'=> 'DAGUA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '243' , 'nombre'=> 'EL AGUILA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '246' , 'nombre'=> 'EL CAIRO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '248' , 'nombre'=> 'EL CERRITO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '250' , 'nombre'=> 'EL DOVIO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '275' , 'nombre'=> 'FLORIDA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '306' , 'nombre'=> 'GINEBRA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '318' , 'nombre'=> 'GUACARI'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '364' , 'nombre'=> 'JAMUNDI'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '377' , 'nombre'=> 'LA CUMBRE'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '400' , 'nombre'=> 'LA UNION'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '403' , 'nombre'=> 'LA VICTORIA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '497' , 'nombre'=> 'OBANDO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '520' , 'nombre'=> 'PALMIRA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '563' , 'nombre'=> 'PRADERA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '606' , 'nombre'=> 'RESTREPO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '616' , 'nombre'=> 'RIOFRIO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '622' , 'nombre'=> 'ROLDANILLO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '670' , 'nombre'=> 'SAN PEDRO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '736' , 'nombre'=> 'SEVILLA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '823' , 'nombre'=> 'TORO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '828' , 'nombre'=> 'TRUJILLO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '834' , 'nombre'=> 'TULUA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '845' , 'nombre'=> 'ULLOA'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '863' , 'nombre'=> 'VERSALLES'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '869' , 'nombre'=> 'VIJES'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '890' , 'nombre'=> 'YOTOCO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '892' , 'nombre'=> 'YUMBO'],
			['departamento_id'=>'24' , 'codigo_divipola'=> '895' , 'nombre'=> 'ZARZAL'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '001' , 'nombre'=> 'ARAUCA'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '065' , 'nombre'=> 'ARAUQUITA'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '220' , 'nombre'=> 'CRAVO NORTE'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '300' , 'nombre'=> 'FORTUL'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '591' , 'nombre'=> 'PUERTO RONDON'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '736' , 'nombre'=> 'SARAVENA'],
			['departamento_id'=>'25' , 'codigo_divipola'=> '794' , 'nombre'=> 'TAME'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '001' , 'nombre'=> 'YOPAL'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '010' , 'nombre'=> 'AGUAZUL'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '015' , 'nombre'=> 'CHAMEZA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '125' , 'nombre'=> 'HATO COROZAL'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '136' , 'nombre'=> 'LA SALINA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '139' , 'nombre'=> 'MANI'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '162' , 'nombre'=> 'MONTERREY'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '225' , 'nombre'=> 'NUNCHIA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '230' , 'nombre'=> 'OROCUE'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '250' , 'nombre'=> 'PAZ DE ARIPORO'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '263' , 'nombre'=> 'PORE'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '279' , 'nombre'=> 'RECETOR'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '300' , 'nombre'=> 'SABANALARGA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '315' , 'nombre'=> 'SACAMA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '325' , 'nombre'=> 'SAN LUIS DE PALENQUE'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '400' , 'nombre'=> 'TAMARA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '410' , 'nombre'=> 'TAURAMENA'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '430' , 'nombre'=> 'TRINIDAD'],
			['departamento_id'=>'26' , 'codigo_divipola'=> '440' , 'nombre'=> 'VILLANUEVA'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '001' , 'nombre'=> 'MOCOA'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '219' , 'nombre'=> 'COLON'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '320' , 'nombre'=> 'ORITO'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '568' , 'nombre'=> 'PUERTO ASIS'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '569' , 'nombre'=> 'PUERTO CAICEDO'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '571' , 'nombre'=> 'PUERTO GUZMAN'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '573' , 'nombre'=> 'LEGUIZAMO'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '749' , 'nombre'=> 'SIBUNDOY'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '755' , 'nombre'=> 'SAN FRANCISCO'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '757' , 'nombre'=> 'SAN MIGUEL'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '760' , 'nombre'=> 'SANTIAGO'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '865' , 'nombre'=> 'VALLE DEL GUAMUEZ'],
			['departamento_id'=>'27' , 'codigo_divipola'=> '885' , 'nombre'=> 'VILLAGARZON'],
			['departamento_id'=>'28' , 'codigo_divipola'=> '001' , 'nombre'=> 'SAN ANDRES'],
			['departamento_id'=>'28' , 'codigo_divipola'=> '564' , 'nombre'=> 'PROVIDENCIA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '001' , 'nombre'=> 'LETICIA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '263' , 'nombre'=> 'EL ENCANTO'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '405' , 'nombre'=> 'LA CHORRERA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '407' , 'nombre'=> 'LA PEDRERA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '430' , 'nombre'=> 'LA VICTORIA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '460' , 'nombre'=> 'MIRITI - PARANA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '530' , 'nombre'=> 'PUERTO ALEGRIA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '536' , 'nombre'=> 'PUERTO ARICA'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '540' , 'nombre'=> 'PUERTO NARIÑO'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '669' , 'nombre'=> 'PUERTO SANTANDER'],
			['departamento_id'=>'29' , 'codigo_divipola'=> '798' , 'nombre'=> 'TARAPACA'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '001' , 'nombre'=> 'INIRIDA'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '343' , 'nombre'=> 'BARRANCO MINAS'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '663' , 'nombre'=> 'MAPIRIPANA'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '883' , 'nombre'=> 'SAN FELIPE'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '884' , 'nombre'=> 'PUERTO COLOMBIA'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '885' , 'nombre'=> 'LA GUADALUPE'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '886' , 'nombre'=> 'CACAHUAL'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '887' , 'nombre'=> 'PANA PANA'],
			['departamento_id'=>'30' , 'codigo_divipola'=> '888' , 'nombre'=> 'MORICHAL'],
			['departamento_id'=>'31' , 'codigo_divipola'=> '001' , 'nombre'=> 'SAN JOSE DEL GUAVIARE'],
			['departamento_id'=>'31' , 'codigo_divipola'=> '015' , 'nombre'=> 'CALAMAR'],
			['departamento_id'=>'31' , 'codigo_divipola'=> '025' , 'nombre'=> 'EL RETORNO'],
			['departamento_id'=>'31' , 'codigo_divipola'=> '200' , 'nombre'=> 'MIRAFLORES'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '001' , 'nombre'=> 'MITU'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '161' , 'nombre'=> 'CARURU'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '511' , 'nombre'=> 'PACOA'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '666' , 'nombre'=> 'TARAIRA'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '777' , 'nombre'=> 'PAPUNAUA'],
			['departamento_id'=>'32' , 'codigo_divipola'=> '889' , 'nombre'=> 'YAVARATE'],
			['departamento_id'=>'33' , 'codigo_divipola'=> '001' , 'nombre'=> 'PUERTO CARREÑO'],
			['departamento_id'=>'33' , 'codigo_divipola'=> '524' , 'nombre'=> 'LA PRIMAVERA'],
			['departamento_id'=>'33' , 'codigo_divipola'=> '624' , 'nombre'=> 'SANTA ROSALIA'],
			['departamento_id'=>'33' , 'codigo_divipola'=> '773' , 'nombre'=> 'CUMARIBO']
         ]);
    }
}
